#!/usr/bin/env bash

BIN=node_modules/.bin
# $BIN/browserify --extension .es6 $1 | $BIN/tape-run2

# with chrome
$BIN/browserify --extension .es6 $1 | $BIN/tape-run2 -b chrome

# debug
# $BIN/browserify --extension .es6 $1 > public/bundle.js
